import localFont from "next/font/local";
import Nav from "./(components)/Nav";
import "./globals.css";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";

config.autoAddCss = false;

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Ticket App",
  description: "Generated by Deega Abdul",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-page`} // Added bg-page here
      >
        <div className="flex flex-col h-screen max-h-screen">
          <Nav />
        </div>
        <div className="flex-grow overflow-y-auto text-default-text">
          {children}
        </div>
      </body>
    </html>
  );
}
